const data = [
  {
    title: "Professeur",
    description: "Former et accompagner les élèves dans leur apprentissage et leur développement intellectuel.",
    value: 55,
    category: "Éducation",
    date: "2026-01-22",
    studies: "Master + concours (5 à 6 ans)",
    salary: "2 000 – 3 500 € / mois",
    skills: ["Pédagogie", "Patience", "Organisation"],
    pros: "Stabilité de l’emploi, utilité sociale",
    cons: "Salaire modéré, charge mentale",
    notes: "Métier stable et utile mais exigeant sur la durée."
  },
  {
    title: "Écrivain",
    description: "Créer des œuvres littéraires et développer un univers créatif personnel.",
    value: 75,
    category: "Création",
    date: "2026-01-20",
    studies: "Variable, autodidacte ou études littéraires (0 à 5 ans)",
    salary: "Très variable",
    skills: ["Créativité", "Discipline", "Expression écrite"],
    pros: "Liberté créative, passion",
    cons: "Instabilité financière",
    notes: "Très enrichissant intellectuellement mais risqué."
  },
  {
    title: "Psychologue",
    description: "Accompagner les patients dans leur santé mentale et leur bien-être.",
    value: 60,
    category: "Santé",
    date: "2026-01-18",
    studies: "Master en psychologie (5 ans)",
    salary: "2 200 – 4 000 € / mois",
    skills: ["Écoute", "Empathie", "Analyse"],
    pros: "Impact humain fort",
    cons: "Charge émotionnelle élevée",
    notes: "Métier noble mais mentalement exigeant."
  },
  {
    title: "Comptable",
    description: "Gérer la comptabilité et les obligations financières des entreprises.",
    value: 65,
    category: "Finance",
    date: "2026-01-16",
    studies: "BTS à DSCG (2 à 5 ans)",
    salary: "2 300 – 4 500 € / mois",
    skills: ["Rigueur", "Organisation", "Analyse"],
    pros: "Sécurité de l’emploi",
    cons: "Travail répétitif",
    notes: "Métier sûr et recherché."
  },
  {
    title: "Conseiller bancaire",
    description: "Accompagner les clients dans la gestion de leurs finances et projets.",
    value: 58,
    category: "Finance",
    date: "2026-01-15",
    studies: "Bac +2 à Bac +5 (2 à 5 ans)",
    salary: "2 200 – 3 800 € / mois",
    skills: ["Relation client", "Négociation", "Analyse"],
    pros: "Contact humain, stabilité",
    cons: "Pression commerciale",
    notes: "Bon compromis stabilité / relationnel."
  },
  {
    title: "Enquêteur",
    description: "Mener des investigations pour recueillir des informations et preuves.",
    value: 62,
    category: "Sécurité",
    date: "2026-01-14",
    studies: "Concours + formation (2 à 4 ans)",
    salary: "2 000 – 3 500 € / mois",
    skills: ["Observation", "Analyse", "Discrétion"],
    pros: "Travail stimulant",
    cons: "Contraintes horaires",
    notes: "Métier dynamique mais exigeant."
  },
  {
    title: "Inspecteur",
    description: "Contrôler, vérifier et faire respecter les lois et règlements.",
    value: 63,
    category: "Fonction publique",
    date: "2026-01-13",
    studies: "Concours + formation (3 à 5 ans)",
    salary: "2 300 – 4 000 € / mois",
    skills: ["Rigueur", "Analyse", "Autorité"],
    pros: "Responsabilités, stabilité",
    cons: "Pression et conflits",
    notes: "Métier sérieux avec responsabilités."
  },
  {
    title: "Juge",
    description: "Rendre la justice en toute impartialité et faire appliquer la loi.",
    value: 78,
    category: "Droit",
    date: "2026-01-12",
    studies: "ENM après Master (7 à 8 ans)",
    salary: "3 000 – 6 000 € / mois",
    skills: ["Analyse", "Neutralité", "Éthique"],
    pros: "Prestige, rôle clé",
    cons: "Forte responsabilité",
    notes: "Carrière exigeante mais très respectée."
  },
  {
    title: "Maire",
    description: "Administrer une commune et représenter les citoyens.",
    value: 57,
    category: "Politique",
    date: "2026-01-11",
    studies: "Aucune durée fixe (variable)",
    salary: "Selon la taille de la commune",
    skills: ["Leadership", "Gestion", "Communication"],
    pros: "Impact local direct",
    cons: "Pression politique",
    notes: "Engagement fort au service des citoyens."
  },
  {
    title: "Politicien",
    description: "Participer aux décisions publiques et orienter les politiques nationales.",
    value: 68,
    category: "Politique",
    date: "2026-01-10",
    studies: "Souvent sciences politiques (3 à 5 ans)",
    salary: "Variable",
    skills: ["Négociation", "Communication", "Stratégie"],
    pros: "Influence, pouvoir décisionnel",
    cons: "Instabilité, exposition médiatique",
    notes: "Carrière influente mais risquée."
  },
  {
    title: "Ingénieur en armement",
    description: "Concevoir et améliorer des systèmes technologiques pour la défense.",
    value: 72,
    category: "Ingénierie",
    date: "2026-01-09",
    studies: "École d’ingénieur (5 ans)",
    salary: "3 500 – 6 000 € / mois",
    skills: ["Maths", "Physique", "Rigueur"],
    pros: "Salaire élevé, haute technicité",
    cons: "Questions éthiques",
    notes: "Très technique, moralement sensible."
  }
];
